[package]
name = "task"
version = "0.1.0"
edition = "2021"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage,coverage_nightly)'] }

[dependencies]
petgraph = "0.7.1"

[dependencies.shared-kernel]
path = "../shared-kernel"

[dependencies.thiserror]
version = "2"
