[package]
name = "task"
version = "0.1.0"
edition = "2021"

[dependencies]
bimap = "0.6.3"
daggy = "0.8.0"

[dependencies.shared-kernel]
path = "../shared-kernel"

[dependencies.thiserror]
version = "2"
